
runtime: custom
env: flex
# entrypoint: gunicorn -b :$PORT extractor.wsgi:application

# runtime_config:
#   python_version: 3.6
  
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: .5
  disk_size_gb: 10